id: VirusTotal V3 Detonate Test
version: -1
name: VirusTotal V3 Detonate Test
description: Tests detonate playbooks of VT v3
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 57e3f975-68ad-41c7-84c2-3589af109cbf
    type: start
    task:
      id: 57e3f975-68ad-41c7-84c2-3589af109cbf
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "1":
    id: "1"
    taskid: 81ccaabd-2840-4562-8185-432e0f8c74d5
    type: regular
    task:
      id: 81ccaabd-2840-4562-8185-432e0f8c74d5
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "2":
    id: "2"
    taskid: 36b8c899-7fcf-408c-84cc-d4f254562c39
    type: regular
    task:
      id: 36b8c899-7fcf-408c-84cc-d4f254562c39
      version: -1
      name: Download FIle
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        complex:
          root: inputs.URL
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "3":
    id: "3"
    taskid: 0df2b88a-d92b-4fab-8bec-ef0ad5d8ca81
    type: playbook
    task:
      id: 0df2b88a-d92b-4fab-8bec-ef0ad5d8ca81
      version: -1
      name: Detonate File - VirusTotal V3
      playbookName: Detonate File - VirusTotal V3
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      FileEntryID:
        complex:
          root: File
          accessor: EntryID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "4":
    id: "4"
    taskid: 18ddafce-8bf7-4de7-87a3-acd29f019d3d
    type: playbook
    task:
      id: 18ddafce-8bf7-4de7-87a3-acd29f019d3d
      version: -1
      name: Detonate URL - VirusTotal V3
      playbookName: Detonate URL - VirusTotal V3
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      URL:
        complex:
          root: inputs.URL
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "5":
    id: "5"
    taskid: f3385504-4709-4f3b-87c5-fbb18f0e85a3
    type: title
    task:
      id: f3385504-4709-4f3b-87c5-fbb18f0e85a3
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: URL
  value:
    simple: https://google.com
  required: false
  description: ""
  playbookInputQuery: null
outputs: []
fromversion: "5.5.0"