id: Unisolate Endpoint - Generic
version: -1
name: Unisolate Endpoint - Generic
description: "This playbook will auto Unisolate endpoints by the endpoint id that\
  \ was provided in the playbook.\nCurrently supports the next integration:\n- Carbon\
  \ Black Response\n- Cortex XDR\n- Crowdstrike Falcon\n- FireEye HX \n- Cybereason\n"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2a0f3a1c-748a-4019-87d4-87a90fbe5bfb
    type: start
    task:
      id: 2a0f3a1c-748a-4019-87d4-87a90fbe5bfb
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
      - "1"
      - "4"
      - "5"
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: fce5d8d1-840a-4878-82fc-807950fd1e48
    type: playbook
    task:
      id: fce5d8d1-840a-4878-82fc-807950fd1e48
      version: -1
      name: Carbon Black Response - Unisolate Endpoint
      description: This playbook will unisolate sensors in Carbon Black Response.
      playbookName: Carbon Black Response - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_ID:
        simple: ${inputs.Endpoint_ID}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "2":
    id: "2"
    taskid: 2bc544fa-97d1-4391-8e24-790da41231c1
    type: playbook
    task:
      id: 2bc544fa-97d1-4391-8e24-790da41231c1
      version: -1
      name: Cortex XDR - Unisolate Endpoint
      description: This playbook will assist you to Unisolate endpoint with Cortex
        XDR.
      playbookName: Cortex XDR - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_ID:
        simple: ${inputs.Endpoint_ID}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "3":
    id: "3"
    taskid: a42fe062-acbe-448c-82c4-f7cdfdf15b82
    type: title
    task:
      id: a42fe062-acbe-448c-82c4-f7cdfdf15b82
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: a108aa9f-d9b9-4594-8f9f-7176e0ea21eb
    type: playbook
    task:
      id: a108aa9f-d9b9-4594-8f9f-7176e0ea21eb
      version: -1
      name: Crowdstrike Falcon - Unisolate Endpoint
      description: This playbook will unisolate endpoints by the device id that was
        provided in the playbook input.
      playbookName: Crowdstrike Falcon - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_id:
        simple: ${inputs.Endpoint_ID}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "5":
    id: "5"
    taskid: af9905f1-9375-444b-8540-addd1b6aee7b
    type: playbook
    task:
      id: af9905f1-9375-444b-8540-addd1b6aee7b
      version: -1
      name: FireEye HX - Unisolate Endpoint
      description: This playbook will auto Isolate endpoints by the endpoint id that
        was provided in the playbook input.
      playbookName: FireEye HX - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_id:
        simple: ${inputs.Endpoint_ID}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "6":
    id: "6"
    taskid: c62f9282-d3f7-44c5-8623-5c87c7295586
    type: playbook
    task:
      id: c62f9282-d3f7-44c5-8623-5c87c7295586
      version: -1
      name: Unisolate Endpoint - Cybereason
      description: 'This playbook will assist you to unisolate endpoints using Cybereason
        integration. '
      playbookName: Unisolate Endpoint - Cybereason
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Hostname:
        simple: ${inputs.Hostname}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Endpoint_ID
  value: {}
  required: false
  description: The endpoint id/device id/sensor id/agent id that you wish to unisolate
  playbookInputQuery:
- key: Hostname
  value: {}
  required: false
  description: The hostname of the endpoint to unisolate using Cybereason.
  playbookInputQuery:
outputs: []
tests:
- Account Enrichment - Generic v2.1 - Test
- Calculate Severity - Generic v2 - Test
- Calculate Severity - Standard - Test
- Test Convert file hash to corresponding hashes
- Dedup - Generic v2 - Test
- Detonate File - Generic Test
- Detonate File - No Files test
- Detonate URL - Generic Test
- Domain Enrichment - Generic v2 - Test
- Email Address Enrichment - Generic v2.1 - Test
- Endpoint Enrichment - Generic v2.1 - Test
- Extract Indicators From File - Generic v2 - Test
- Field polling test
- File Enrichment - Generic v2 - Test
- Generic Polling Test
- IP Enrichment - Generic v2 - Test
- Retrieve File from Endpoint - Generic V2 Test
- Send Investigation Summary Reports - Test
- test-domain-indicator
- URL Enrichment - Generic v2 - Test
- Wait Until Datetime - Test
fromversion: 5.5.0
