id: PAN-OS to Cortex Data Lake Monitoring - Cron Job
version: -1
name: PAN-OS to Cortex Data Lake Monitoring - Cron Job
description: |-
  This playbook verifies that your FWs sent logs to the Cortex Data Lake in the last 12 hours. An email notification will be sent if it's not the case.
  This playbook is designed to run as a job.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 27a34995-c8e7-41a5-86a8-cf438c85a1ae
    type: start
    task:
      id: 27a34995-c8e7-41a5-86a8-cf438c85a1ae
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 2a3c9991-bbd2-49bf-8aa8-2c84f2122844
    type: regular
    task:
      id: 2a3c9991-bbd2-49bf-8aa8-2c84f2122844
      version: -1
      name: PANOStoCortexDataLakeMonitoring
      description: "Used to verify that all firewalls successfully pushed logs to\
        \ the Cortex Data Lake for the last 12 hours. It's an easy way to do monitoring\
        \ of the FW connection to CDL.\nYou can use either a list of FW serials or\
        \ PAN-OS integration to define the list of FW to be monitored. "
      scriptName: PANOStoCortexDataLakeMonitoring
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      fw_serials:
        complex:
          root: inputs.fw_serials
      pan_os_integration_instance_name:
        simple: pan_os_pano_8.1_ 56111
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 06112ffe-942b-45c0-875e-c4dffbb1947a
    type: condition
    task:
      id: 06112ffe-942b-45c0-875e-c4dffbb1947a
      version: -1
      name: Any Log connection issue?
      description: Any Log connection issue?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: CDL.monitoring
                accessor: FirewallsWithoutLogsSent
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 1c3358a5-dc13-4365-828c-77ec95026bef
    type: title
    task:
      id: 1c3358a5-dc13-4365-828c-77ec95026bef
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 35905371-50e8-4779-8909-7c1da70ce5fc
    type: title
    task:
      id: 35905371-50e8-4779-8909-7c1da70ce5fc
      version: -1
      name: PAN-OS to Cortex Data Lake log forwarding problem detected
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 68a5fcab-92fb-4116-8e14-30cb589d2456
    type: regular
    task:
      id: 68a5fcab-92fb-4116-8e14-30cb589d2456
      version: -1
      name: Send notification to the registered email address
      description: Sends an email using EWS.
      script: '|||send-mail'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      body:
        simple: |-
          This(these) firewall(s) didn't send logs to Cortex Data Lake for the last 12 hours:
          ${CDL.monitoring.FirewallsWithoutLogsSent}

          I think you should have a look.

          Best regards,
          DBot
      subject:
        simple: CORTEX XDR / Problem / some FWs are not logging anymore to Cortex
          Data Lake
      to:
        complex:
          root: inputs.email_notification
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: a037fd37-04b8-4b64-805b-226f4e806ddc
    type: regular
    task:
      id: a037fd37-04b8-4b64-805b-226f4e806ddc
      version: -1
      name: Set Incident Severity to Informational
      description: Optionally increases the incident severity to the new value if
        it is greater than the existing severity.
      scriptName: IncreaseIncidentSeverity
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      severity:
        simple: Informational
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 94b857a6-fbc7-4d35-8952-51f755c3b9b6
    type: title
    task:
      id: 94b857a6-fbc7-4d35-8952-51f755c3b9b6
      version: -1
      name: No PAN-OS to Cortex Data Lake log forwarding issues detected
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1055
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 8f49a5d9-f902-41c1-8f5c-140a2cc2496e
    type: regular
    task:
      id: 8f49a5d9-f902-41c1-8f5c-140a2cc2496e
      version: -1
      name: Close Investigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: a0a037f8-f3ec-40c6-8776-48d95e1d7c6b
    type: regular
    task:
      id: a0a037f8-f3ec-40c6-8776-48d95e1d7c6b
      version: -1
      name: Set incident name
      description: Change the properties of an incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      name:
        simple: CDL Monitoring
      type:
        simple: Cortex Data Lake Monitoring
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: eea37dc3-d365-450f-8e9b-c026c1b6e169
    type: regular
    task:
      id: eea37dc3-d365-450f-8e9b-c026c1b6e169
      version: -1
      name: Update closing reason without any action required
      description: Change the properties of an incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      closeNotes:
        simple: Everything is OK
      closeReason:
        simple: Everything is OK
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: a19cfcbd-7302-4850-884b-f73f29d128d0
    type: regular
    task:
      id: a19cfcbd-7302-4850-884b-f73f29d128d0
      version: -1
      name: Update closing reason with the action required
      description: Change the properties of an incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      closeNotes:
        simple: Firewall serials are not sending logs to Cortex Data Lake. Investigation
          required.
      closeReason:
        simple: Firewall serials are not sending logs to Cortex Data Lake. Investigation
          required.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 3eec757c-1a55-466e-8983-023900c12d75
    type: regular
    task:
      id: 3eec757c-1a55-466e-8983-023900c12d75
      version: -1
      name: Create an incident for tracking purposes
      description: Create a new incident
      script: Builtin|||createNewIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      details:
        simple: "At least one of our firewalls did not send successfully logs to the\
          \ Cortex Data Lake for the last 12 hours:\n${CDL.monitoring.FirewallsWithoutLogsSent}\n\
          \nAn email has been sent to ${inputs.email_notification} for notification.\
          \ \n\nCould you please i nvestigate this connectivity issue?\n\nThanks,\n\
          DBot.\n"
      name:
        simple: Cortex Data Lake FW logging problem
      severity:
        simple: High
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 482dec00-2a00-4922-861d-3f8205d76295
    type: regular
    task:
      id: 482dec00-2a00-4922-861d-3f8205d76295
      version: -1
      name: Set incident Severity
      description: Change the properties of an incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      name:
        simple: CDL Monitoring
      severity:
        simple: "3"
      type:
        simple: Cortex Data Lake Monitoring
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1755,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: fw_serials
  value:
    simple: ${incident.fwserials}
  required: false
  description: A comma-separated list of FW serials to monitor. Only applicable if
    no PAN-OS integration name was specified.
  playbookInputQuery:
- key: pan_os_integration_instance_name
  value:
    simple: pan_os_pano_8.1_ 56111
  required: false
  description: Name of the Panorama integration instance to gather the list of monitored
    FWs. If none specified, the list of serials must be provided manually as "fw_serials".
  playbookInputQuery:
- key: email_notification
  value:
    simple: ${incident.email}
  required: false
  description: Email address to send a notification to in case detected problem.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.0.0
