id: PAN-OS to Cortex Data Lake Monitoring - Cron Job
version: -1
name: PAN-OS to Cortex Data Lake Monitoring - Cron Job
description: |-
  This playbook verifies that your FWs sent logs to the Cortex Data Lake in the last 12 hours. An email notification will be sent if it's not the case.
  This playbook is designed to run as a job.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5e7f3017-45e7-4c74-866a-6d5f2e58a4be
    type: start
    task:
      id: 5e7f3017-45e7-4c74-866a-6d5f2e58a4be
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 5123d8ce-cc96-4c47-83be-afce2f6cb0c6
    type: regular
    task:
      id: 5123d8ce-cc96-4c47-83be-afce2f6cb0c6
      version: -1
      name: PANOStoCortexDataLakeMonitoring
      description: "Used to verify that all firewalls successfully pushed logs to
        the Cortex Data Lake for the last 12 hours. It's an easy way to do monitoring
        of the FW connection to CDL.\nYou can use either a list of FW serials or PAN-OS
        integration to define the list of FW to be monitored. "
      scriptName: PANOStoCortexDataLakeMonitoring
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      fw_serials:
        complex:
          root: inputs.fw_serials
      pan_os_integration_instance_name:
        complex:
          root: inputs.panos_integration_instance_name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: acf01449-06d2-40fe-837d-ed62ebec7043
    type: condition
    task:
      id: acf01449-06d2-40fe-837d-ed62ebec7043
      version: -1
      name: Any Log connection issue?
      description: Any Log connection issue?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: CDL.monitoring
                accessor: FirewallsWithoutLogsSent
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: e703aed4-e058-4578-8fdc-d8cdfe164601
    type: title
    task:
      id: e703aed4-e058-4578-8fdc-d8cdfe164601
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1740
        }
      }
    note: false
  "5":
    id: "5"
    taskid: c6ea36de-0211-47a7-81c9-6a85f6a7eb30
    type: title
    task:
      id: c6ea36de-0211-47a7-81c9-6a85f6a7eb30
      version: -1
      name: PAN-OS to Cortex Data Lake log forwarding problem detected
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 64b3503b-3926-430a-8dad-2be952199995
    type: regular
    task:
      id: 64b3503b-3926-430a-8dad-2be952199995
      version: -1
      name: Send notification to the registered email address
      description: Send an email
      script: Mail Sender (New)|||send-mail
      type: regular
      iscommand: true
      brand: Mail Sender (New)
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      body:
        simple: |-
          This(these) firewall(s) didn't send logs to Cortex Data Lake for the last 12 hours:
          ${CDL.monitoring.FirewallsWithoutLogsSent}

          I think you should have a look.

          Best regards,
          DBot
      subject:
        simple: CORTEX XDR / Problem / some FWs are not logging anymore to Cortex
          Data Lake
      to:
        simple: ${inputs.email_notification}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1040
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 835dead9-5141-427b-8928-752e6382696b
    type: regular
    task:
      id: 835dead9-5141-427b-8928-752e6382696b
      version: -1
      name: Set Incident Severity to High
      description: Optionally increases the incident severity to the new value if
        it is greater than the existing severity.
      scriptName: IncreaseIncidentSeverity
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      severity:
        simple: High
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 865
        }
      }
    note: false
  "8":
    id: "8"
    taskid: b87c4401-5b3f-4860-8124-e997d7caaa9f
    type: regular
    task:
      id: b87c4401-5b3f-4860-8124-e997d7caaa9f
      version: -1
      name: Set Incident Severity to Informational
      description: Optionally increases the incident severity to the new value if
        it is greater than the existing severity.
      scriptName: IncreaseIncidentSeverity
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      severity:
        simple: Informational
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 531b782a-be09-4ec9-8ab8-4f93ba8aace5
    type: title
    task:
      id: 531b782a-be09-4ec9-8ab8-4f93ba8aace5
      version: -1
      name: No PAN-OS to Cortex Data Lake log forwarding issues detected
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1055
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 340f8c35-5de6-4727-8536-36e13ef382e5
    type: regular
    task:
      id: 340f8c35-5de6-4727-8536-36e13ef382e5
      version: -1
      name: Close Investigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1565
        }
      }
    note: false
  "11":
    id: "11"
    taskid: ba22e7bf-18ca-43c6-8790-9e0e85c95418
    type: regular
    task:
      id: ba22e7bf-18ca-43c6-8790-9e0e85c95418
      version: -1
      name: Set incident name
      description: Change the properties of an incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      name:
        simple: CDL Monitoring
      type:
        simple: Cortex Data Lake Monitoring
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 0a3da10e-d8d8-4a10-850a-9094cf4ceec0
    type: regular
    task:
      id: 0a3da10e-d8d8-4a10-850a-9094cf4ceec0
      version: -1
      name: Update closing reason without any action required
      description: Change the properties of an incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      closeNotes:
        simple: Everything is OK
      closeReason:
        simple: Everything is OK
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
    note: false
  "13":
    id: "13"
    taskid: a7c97a1a-5266-47e4-8d43-421979a97ecb
    type: regular
    task:
      id: a7c97a1a-5266-47e4-8d43-421979a97ecb
      version: -1
      name: Update closing reason with the action required
      description: Change the properties of an incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      closeNotes:
        simple: Firewall serials are not sending logs to Cortex Data Lake. Investigation
          required.
      closeReason:
        simple: Firewall serials are not sending logs to Cortex Data Lake. Investigation
          required.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1390
        }
      }
    note: false
  "14":
    id: "14"
    taskid: e0ae32e1-ac7b-4cee-8b02-2fa43ed386fa
    type: regular
    task:
      id: e0ae32e1-ac7b-4cee-8b02-2fa43ed386fa
      version: -1
      name: Create an incident for tracking purposes
      description: Create a new incident
      script: Builtin|||createNewIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      details:
        simple: "At least one of our firewalls did not send successfully logs to the
          Cortex Data Lake for the last 12 hours:\n${CDL.monitoring.FirewallsWithoutLogsSent}\n\nAn email
          has been sent to ${inputs.email_notification} for notification. \n\nCould
          you please investigate this connectivity issue?\n\nThanks,\nDBot.\n"
      name:
        simple: Cortex Data Lake FW logging problem
      severity:
        simple: High
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1215
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1755,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: fw_serials
  value:
    simple: ${incident.fwserials}
  required: false
  description: A comma-separated list of FW serials to monitor. Only applicable if
    no PAN-OS integration name was specified.
  playbookInputQuery: null
- key: pan_os_integration_instance_name
  value:
    simple: ${incident.panosintegrationinstancename}
  required: false
  description: Name of the Panorama integration instance to gather the list of monitored FWs.
    If none specified, the list of serials must be provided manually as "fw_serials".
  playbookInputQuery: null
- key: email_notification
  value:
    simple: ${incident.email}
  required: false
  description: Email address to send a notification to in case detected problem.
  playbookInputQuery: null
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.0.0