id: Crowdstrike Falcon - Unisolate Endpoint
version: -1
name: Crowdstrike Falcon - Unisolate Endpoint
description: This playbook will unisolate endpoints by the device id that was provided
  in the playbook input.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: acf803ed-f899-4175-8396-c5b48ac766df
    type: start
    task:
      id: acf803ed-f899-4175-8396-c5b48ac766df
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 5cb230a3-e04f-42d6-884d-af92579701e5
    type: condition
    task:
      id: 5cb230a3-e04f-42d6-884d-af92579701e5
      version: -1
      name: Is Crowdstrike Falcon enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    scriptarguments:
      brandname:
        simple: CrowdstrikeFalcon
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 343486ae-6c5a-4d2c-8814-beb66bceb37a
    type: title
    task:
      id: 343486ae-6c5a-4d2c-8814-beb66bceb37a
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: b362cd4c-9726-4661-8023-0961c366c854
    type: condition
    task:
      id: b362cd4c-9726-4661-8023-0961c366c854
      version: -1
      name: Is there device id?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.Device_id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 750,
          "y": 460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 84f4a4a8-bea4-4cc7-861d-09ae4cbc575a
    type: regular
    task:
      id: 84f4a4a8-bea4-4cc7-861d-09ae4cbc575a
      version: -1
      name: Get device info
      description: Searches for a device that matches the query.
      script: '|||cs-falcon-search-device'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      filter: {}
      hostname: {}
      ids:
        simple: ${inputs.Device_id}
      platform_name: {}
      site_name: {}
      status: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 960,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 9d8b8ea0-4423-414f-81cf-1477e00d7ab8
    type: condition
    task:
      id: 9d8b8ea0-4423-414f-81cf-1477e00d7ab8
      version: -1
      name: 'Is device contained? '
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CrowdStrike.Device.Status
            iscontext: true
          right:
            value:
              simple: contained
    view: |-
      {
        "position": {
          "x": 960,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 57eff90f-06d5-49d8-8a50-2837adb7357e
    type: regular
    task:
      id: 57eff90f-06d5-49d8-8a50-2837adb7357e
      version: -1
      name: Unisolate device
      description: Lifts containment on the host, which returns its network communications
        to normal.
      script: '|||cs-falcon-lift-host-containment'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      ids:
        simple: ${inputs.Device_id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1190,
          "y": 1080
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "1_2_no": 0.52,
      "5_2_#default#": 0.48
    },
    "paper": {
      "dimensions": {
        "height": 1515,
        "width": 1120,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: Endpoint_id
  value: {}
  required: false
  description: 'The endpoint id/device id that you wish to unisolate. '
  playbookInputQuery:
outputs: []
tests:
- Test - CrowdStrike Falcon
fromversion: 5.5.0
