id: Create Zip from VirusTotal
version: -1
name: Create Zip from VirusTotal
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5b898b60-6014-4089-89c6-9aab58a0cd91
    type: start
    task:
      id: 5b898b60-6014-4089-89c6-9aab58a0cd91
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 9bc668ca-6aff-43a4-804f-55a09a434ad9
    type: regular
    task:
      id: 9bc668ca-6aff-43a4-804f-55a09a434ad9
      version: -1
      name: Create zip
      description: Creates a password-protected ZIP file containing files from VirusTotal.
      script: VirusTotal - Premium - (API v3)|||vt-private-zip-create
      type: regular
      iscommand: true
      brand: VirusTotal - Premium - (API v3)
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      file:
        complex:
          root: inputs.password
      password: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 5497dbb5-7a28-4ef9-8202-452794524f93
    type: playbook
    task:
      id: 5497dbb5-7a28-4ef9-8202-452794524f93
      version: -1
      name: GenericPolling
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          root: VirusTotal.Zip
          accessor: id
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: ids
      PollingCommandName:
        simple: vt-private-zip-get
      Timeout:
        simple: "10"
      dt:
        simple: VirusTotal.Zip.attributes(val.status != "finished")
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 6f5ee822-50ed-4cd9-8261-0f401bf6d889
    type: regular
    task:
      id: 6f5ee822-50ed-4cd9-8261-0f401bf6d889
      version: -1
      name: Get zip details
      description: Retrieve information about a ZIP file.
      script: VirusTotal - Premium - (API v3)|||vt-private-zip-get
      type: regular
      iscommand: true
      brand: VirusTotal - Premium - (API v3)
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      zip_id:
        complex:
          root: VirusTotal.Zip
          accessor: id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: f3ab25bb-042e-46d3-8b01-f427b3eab581
    type: condition
    task:
      id: f3ab25bb-042e-46d3-8b01-f427b3eab581
      version: -1
      name: Check the zip is finished
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: VirusTotal.Zip.attributes
                accessor: status
            iscontext: true
          right:
            value:
              simple: finished
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: ded38b91-8590-400e-8ddf-abd3ca74c53a
    type: condition
    task:
      id: ded38b91-8590-400e-8ddf-abd3ca74c53a
      version: -1
      name: Should download the file?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              complex:
                root: inputs.download_zip
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: fd71f4f1-6b6a-4d95-8955-835edd9dab7c
    type: title
    task:
      id: fd71f4f1-6b6a-4d95-8955-835edd9dab7c
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1085
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: de68ad47-373e-4101-8a23-3603dcfd4063
    type: regular
    task:
      id: de68ad47-373e-4101-8a23-3603dcfd4063
      version: -1
      name: Download File
      description: Creates a password-protected ZIP file containing files from VirusTotal.
      script: VirusTotal - Premium - (API v3)|||vt-private-zip-create
      type: regular
      iscommand: true
      brand: VirusTotal - Premium - (API v3)
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      file:
        complex:
          root: inputs.hashes_to_zip
      password: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 1173c397-7cd0-41f2-8921-ddb5daa49197
    type: title
    task:
      id: 1173c397-7cd0-41f2-8921-ddb5daa49197
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: e8f569c1-26ec-4793-8207-79b6958d17df
    type: regular
    task:
      id: e8f569c1-26ec-4793-8207-79b6958d17df
      version: -1
      name: Raise error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Zipping file is not over. Try to check if the file is zipped later.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 1025,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: hashes_to_zip
  value:
    complex:
      root: File
      accessor: MD5
  required: true
  description: Which hashes you want to zip.
  playbookInputQuery:
- key: download_zip
  value:
    simple: "false"
  required: false
  description: Should I download the zip after creation?
  playbookInputQuery:
outputs: []
tests:
- VirusTotal Premium v3 TestPlaybook
fromversion: 5.5.0
description: Creates a zip from given hashes exists in VirusTotal
